baseurl: "/blog"
title: "Mein Projekt"
description: "Eine statische Website mit Jekyll & GitHub Pages"
theme: minima

plugins:
  - jekyll-feed

sass:
  style: compressed
include:
  - css/style.scss

minima:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"
    - title: "My Projects"
      url: "/projects/"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
