site_name: Mein Blog
docs_dir: .
nav:
  - Startseite: index.md
    - Über: about.md
  - Blog: blog.md
  - Beiträge:
      - Beitrag 1: posts/beitrag1.md
      - Beitrag 2: posts/beitrag2.md
theme:
  name: readthedocs
plugins:
  - search
